version: '3.2'

services:

  proxy:
    image: nginx:latest
    container_name: ghostproxy
    restart: always
    volumes:
       - type: bind
         source: ./conf.d
         target: /etc/nginx/conf.d/
       - type: bind
         source: ./ghost.local
         target: /usr/share/nginx/ghost.local
    ports:
      - 80:80
    environment:
      - TERM=xterm
    networks:
      - mynet

  ghost:
    # image: ghost:3-alpine
    image: kaml/nginx
    container_name: ghost
    restart: always
    # ports:
    #   - 3050:2368
    volumes:
      - content:/var/lib/ghost/content
    environment:
      url: http://ghost.local
      database__client: mysql
      database__connection__host: database
      database__connection__port: 3306
      database__connection__database: ghost
      database__connection__user: root
      database__connection__password: p1ssword
    networks:
      - mynet

  database:
    image: mysql:5.7
    container_name: ghostdb
    restart: always
    # ports:
    #   - 3306:3306
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ghost
      MYSQL_ROOT_PASSWORD: p1ssword
    networks:
      - mynet

volumes:
  content:
  data:

networks:
  mynet:
    driver: bridge