version: '3.2'

services:
  # blastradius:
  #   image: local/blastradius
  #   build:
  #     context: ./build/.
  #   cap_add:
  #     - SYS_ADMIN
  #   security_opt:
  #     - apparmor:unconfined


  tf-lint:
    image: bridgecrew/checkov:2
    container_name: tf-lint
    working_dir: /tf
    command: -d /tf --quiet
    volumes:
      - type: bind
        source: ./tf
        target: /tf

  terraform:
    image: hashicorp/terraform:1.0.8
    container_name: terraform
    working_dir: /tf
    command: ${TF_ACTION}
    volumes:
      - type: bind
        source: ./tf
        target: /tf
      # only required for service principal certificate if used for authentication
      - type: bind
        source: ./auth
        target: /home/klagan/source/github/samples-docker/cloud-provisioner/auth
    environment:
      - ARM_CLIENT_ID
      - ARM_CLIENT_CERTIFICATE_PATH
      - ARM_SUBSCRIPTION_ID
      - ARM_TENANT_ID
      - ARM_ACCESS_KEY
      - ARM_CLIENT_CERTIFICATE_PASSWORD
      - TF_ACTION
