version: '3.2'

services:
  ghost:
    image: ghost:3-alpine
    container_name: ghost
    restart: always
    ports:
      - 3050:2368
    volumes:
      - content:/var/lib/ghost/content
    environment:
      url: http://localhost:3050
      database__client: mysql
      database__connection__host: database
      database__connection__port: 3306
      database__connection__database: ghost
      database__connection__user: root
      database__connection__password: pissword

  database:
    image: mysql:5.7
    container_name: ghostdb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ghost
      MYSQL_ROOT_PASSWORD: pissword

volumes:
  content:
  data: